// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package handler

import (
	"net/http"

	assigned "MuXiFresh-Be-2.0/app/task/cmd/api/internal/handler/assigned"
	comment "MuXiFresh-Be-2.0/app/task/cmd/api/internal/handler/comment"
	submitted "MuXiFresh-Be-2.0/app/task/cmd/api/internal/handler/submitted"
	"MuXiFresh-Be-2.0/app/task/cmd/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				// 布置/修改指定作业(题目)
				Method:  http.MethodPost,
				Path:    "/assigned",
				Handler: assigned.SetAssignmentHandler(serverCtx),
			},
			{
				// 获取指定作业信息(题目)
				Method:  http.MethodGet,
				Path:    "/assigned/:id",
				Handler: assigned.GetAssignmentInfoHandler(serverCtx),
			},
			{
				// 删除指定作业(题目)
				Method:  http.MethodDelete,
				Path:    "/assigned/:id",
				Handler: assigned.DelAssignmentHandler(serverCtx),
			},
			{
				// 获取作业列表(题目)
				Method:  http.MethodGet,
				Path:    "/assigned/list",
				Handler: assigned.GetAssignmentListHandler(serverCtx),
			},
			{
				// 获取作业列表（组别 年份 学期）
				Method:  http.MethodGet,
				Path:    "/assigned/list/selected",
				Handler: assigned.GetAssignmentListSelectedHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.JwtAuth.AccessSecret),
		rest.WithPrefix("/api/v2/task"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// 获取指定作业的评论
				Method:  http.MethodGet,
				Path:    "/submitted/:id/comment",
				Handler: comment.GetSubmissionCommentHandler(serverCtx),
			},
			{
				// 评论指定作业
				Method:  http.MethodPost,
				Path:    "/submitted/:id/comment",
				Handler: comment.SetSubmissionCommentHandler(serverCtx),
			},
			{
				// 回复指定评论
				Method:  http.MethodPost,
				Path:    "/submitted/:id/comment/reply",
				Handler: comment.ReplySubmissionCommentHandler(serverCtx),
			},
			{
				// 删除指定评论
				Method:  http.MethodDelete,
				Path:    "/submitted/comment/:id",
				Handler: comment.DelSubmissionCommentHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.JwtAuth.AccessSecret),
		rest.WithPrefix("/api/v2/task"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// 查看指定作业所有人完成情况
				Method:  http.MethodGet,
				Path:    "/assigned/:id/completion",
				Handler: submitted.GetAllSubmissionStatusHandler(serverCtx),
			},
			{
				// 我的某作业提交状态
				Method:  http.MethodGet,
				Path:    "/assigned/:id/status",
				Handler: submitted.GetMySubmissionStatusHandler(serverCtx),
			},
			{
				// 提交/修改作业
				Method:  http.MethodPost,
				Path:    "/submitted",
				Handler: submitted.SetSubmissionHandler(serverCtx),
			},
			{
				// 获取指定的作业提交
				Method:  http.MethodGet,
				Path:    "/submitted",
				Handler: submitted.GetSubmissionInfoHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.JwtAuth.AccessSecret),
		rest.WithPrefix("/api/v2/task"),
	)
}
