// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v4.25.3
// source: submission.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// status
type GetMySubmissionStatusReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AssignmentID  string                 `protobuf:"bytes,1,opt,name=AssignmentID,proto3" json:"AssignmentID,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=UserId,proto3" json:"UserId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMySubmissionStatusReq) Reset() {
	*x = GetMySubmissionStatusReq{}
	mi := &file_submission_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMySubmissionStatusReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMySubmissionStatusReq) ProtoMessage() {}

func (x *GetMySubmissionStatusReq) ProtoReflect() protoreflect.Message {
	mi := &file_submission_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMySubmissionStatusReq.ProtoReflect.Descriptor instead.
func (*GetMySubmissionStatusReq) Descriptor() ([]byte, []int) {
	return file_submission_proto_rawDescGZIP(), []int{0}
}

func (x *GetMySubmissionStatusReq) GetAssignmentID() string {
	if x != nil {
		return x.AssignmentID
	}
	return ""
}

func (x *GetMySubmissionStatusReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetMySubmissionStatusResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=Status,proto3" json:"Status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMySubmissionStatusResp) Reset() {
	*x = GetMySubmissionStatusResp{}
	mi := &file_submission_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMySubmissionStatusResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMySubmissionStatusResp) ProtoMessage() {}

func (x *GetMySubmissionStatusResp) ProtoReflect() protoreflect.Message {
	mi := &file_submission_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMySubmissionStatusResp.ProtoReflect.Descriptor instead.
func (*GetMySubmissionStatusResp) Descriptor() ([]byte, []int) {
	return file_submission_proto_rawDescGZIP(), []int{1}
}

func (x *GetMySubmissionStatusResp) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

// set
type SetSubmissionReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AssignmentID  string                 `protobuf:"bytes,1,opt,name=AssignmentID,proto3" json:"AssignmentID,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=UserId,proto3" json:"UserId,omitempty"`
	Urls          []string               `protobuf:"bytes,3,rep,name=Urls,proto3" json:"Urls,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetSubmissionReq) Reset() {
	*x = SetSubmissionReq{}
	mi := &file_submission_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetSubmissionReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetSubmissionReq) ProtoMessage() {}

func (x *SetSubmissionReq) ProtoReflect() protoreflect.Message {
	mi := &file_submission_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetSubmissionReq.ProtoReflect.Descriptor instead.
func (*SetSubmissionReq) Descriptor() ([]byte, []int) {
	return file_submission_proto_rawDescGZIP(), []int{2}
}

func (x *SetSubmissionReq) GetAssignmentID() string {
	if x != nil {
		return x.AssignmentID
	}
	return ""
}

func (x *SetSubmissionReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *SetSubmissionReq) GetUrls() []string {
	if x != nil {
		return x.Urls
	}
	return nil
}

type SetSubmissionResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Flag          bool                   `protobuf:"varint,1,opt,name=Flag,proto3" json:"Flag,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetSubmissionResp) Reset() {
	*x = SetSubmissionResp{}
	mi := &file_submission_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetSubmissionResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetSubmissionResp) ProtoMessage() {}

func (x *SetSubmissionResp) ProtoReflect() protoreflect.Message {
	mi := &file_submission_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetSubmissionResp.ProtoReflect.Descriptor instead.
func (*SetSubmissionResp) Descriptor() ([]byte, []int) {
	return file_submission_proto_rawDescGZIP(), []int{3}
}

func (x *SetSubmissionResp) GetFlag() bool {
	if x != nil {
		return x.Flag
	}
	return false
}

// info
type GetSubmissionInfoReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AssignmentID  string                 `protobuf:"bytes,1,opt,name=AssignmentID,proto3" json:"AssignmentID,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=UserId,proto3" json:"UserId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSubmissionInfoReq) Reset() {
	*x = GetSubmissionInfoReq{}
	mi := &file_submission_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSubmissionInfoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSubmissionInfoReq) ProtoMessage() {}

func (x *GetSubmissionInfoReq) ProtoReflect() protoreflect.Message {
	mi := &file_submission_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSubmissionInfoReq.ProtoReflect.Descriptor instead.
func (*GetSubmissionInfoReq) Descriptor() ([]byte, []int) {
	return file_submission_proto_rawDescGZIP(), []int{4}
}

func (x *GetSubmissionInfoReq) GetAssignmentID() string {
	if x != nil {
		return x.AssignmentID
	}
	return ""
}

func (x *GetSubmissionInfoReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetSubmissionInfoResp struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	SubmissionInfos []*SubmissionInfo      `protobuf:"bytes,1,rep,name=SubmissionInfos,proto3" json:"SubmissionInfos,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetSubmissionInfoResp) Reset() {
	*x = GetSubmissionInfoResp{}
	mi := &file_submission_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSubmissionInfoResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSubmissionInfoResp) ProtoMessage() {}

func (x *GetSubmissionInfoResp) ProtoReflect() protoreflect.Message {
	mi := &file_submission_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSubmissionInfoResp.ProtoReflect.Descriptor instead.
func (*GetSubmissionInfoResp) Descriptor() ([]byte, []int) {
	return file_submission_proto_rawDescGZIP(), []int{5}
}

func (x *GetSubmissionInfoResp) GetSubmissionInfos() []*SubmissionInfo {
	if x != nil {
		return x.SubmissionInfos
	}
	return nil
}

type SubmissionInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SubmissionID  string                 `protobuf:"bytes,1,opt,name=SubmissionID,proto3" json:"SubmissionID,omitempty"`
	Urls          []string               `protobuf:"bytes,2,rep,name=Urls,proto3" json:"Urls,omitempty"`
	Time          string                 `protobuf:"bytes,3,opt,name=Time,proto3" json:"Time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmissionInfo) Reset() {
	*x = SubmissionInfo{}
	mi := &file_submission_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmissionInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmissionInfo) ProtoMessage() {}

func (x *SubmissionInfo) ProtoReflect() protoreflect.Message {
	mi := &file_submission_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmissionInfo.ProtoReflect.Descriptor instead.
func (*SubmissionInfo) Descriptor() ([]byte, []int) {
	return file_submission_proto_rawDescGZIP(), []int{6}
}

func (x *SubmissionInfo) GetSubmissionID() string {
	if x != nil {
		return x.SubmissionID
	}
	return ""
}

func (x *SubmissionInfo) GetUrls() []string {
	if x != nil {
		return x.Urls
	}
	return nil
}

func (x *SubmissionInfo) GetTime() string {
	if x != nil {
		return x.Time
	}
	return ""
}

// all status
type GetAllSubmissionStatusReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AssignmentID  string                 `protobuf:"bytes,1,opt,name=AssignmentID,proto3" json:"AssignmentID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllSubmissionStatusReq) Reset() {
	*x = GetAllSubmissionStatusReq{}
	mi := &file_submission_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllSubmissionStatusReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllSubmissionStatusReq) ProtoMessage() {}

func (x *GetAllSubmissionStatusReq) ProtoReflect() protoreflect.Message {
	mi := &file_submission_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllSubmissionStatusReq.ProtoReflect.Descriptor instead.
func (*GetAllSubmissionStatusReq) Descriptor() ([]byte, []int) {
	return file_submission_proto_rawDescGZIP(), []int{7}
}

func (x *GetAllSubmissionStatusReq) GetAssignmentID() string {
	if x != nil {
		return x.AssignmentID
	}
	return ""
}

type Completion struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=UserId,proto3" json:"UserId,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	Avatar        string                 `protobuf:"bytes,3,opt,name=Avatar,proto3" json:"Avatar,omitempty"`
	Email         string                 `protobuf:"bytes,4,opt,name=Email,proto3" json:"Email,omitempty"`
	Grade         string                 `protobuf:"bytes,5,opt,name=Grade,proto3" json:"Grade,omitempty"`
	School        string                 `protobuf:"bytes,6,opt,name=School,proto3" json:"School,omitempty"`
	Status        string                 `protobuf:"bytes,7,opt,name=Status,proto3" json:"Status,omitempty"`
	Version       int64                  `protobuf:"varint,8,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Completion) Reset() {
	*x = Completion{}
	mi := &file_submission_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Completion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Completion) ProtoMessage() {}

func (x *Completion) ProtoReflect() protoreflect.Message {
	mi := &file_submission_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Completion.ProtoReflect.Descriptor instead.
func (*Completion) Descriptor() ([]byte, []int) {
	return file_submission_proto_rawDescGZIP(), []int{8}
}

func (x *Completion) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Completion) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Completion) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *Completion) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *Completion) GetGrade() string {
	if x != nil {
		return x.Grade
	}
	return ""
}

func (x *Completion) GetSchool() string {
	if x != nil {
		return x.School
	}
	return ""
}

func (x *Completion) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Completion) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

type GetAllSubmissionStatusResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Completions   []*Completion          `protobuf:"bytes,1,rep,name=Completions,proto3" json:"Completions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllSubmissionStatusResp) Reset() {
	*x = GetAllSubmissionStatusResp{}
	mi := &file_submission_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllSubmissionStatusResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllSubmissionStatusResp) ProtoMessage() {}

func (x *GetAllSubmissionStatusResp) ProtoReflect() protoreflect.Message {
	mi := &file_submission_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllSubmissionStatusResp.ProtoReflect.Descriptor instead.
func (*GetAllSubmissionStatusResp) Descriptor() ([]byte, []int) {
	return file_submission_proto_rawDescGZIP(), []int{9}
}

func (x *GetAllSubmissionStatusResp) GetCompletions() []*Completion {
	if x != nil {
		return x.Completions
	}
	return nil
}

var File_submission_proto protoreflect.FileDescriptor

const file_submission_proto_rawDesc = "" +
	"\n" +
	"\x10submission.proto\x12\n" +
	"submission\"V\n" +
	"\x18GetMySubmissionStatusReq\x12\"\n" +
	"\fAssignmentID\x18\x01 \x01(\tR\fAssignmentID\x12\x16\n" +
	"\x06UserId\x18\x02 \x01(\tR\x06UserId\"3\n" +
	"\x19GetMySubmissionStatusResp\x12\x16\n" +
	"\x06Status\x18\x01 \x01(\tR\x06Status\"b\n" +
	"\x10SetSubmissionReq\x12\"\n" +
	"\fAssignmentID\x18\x01 \x01(\tR\fAssignmentID\x12\x16\n" +
	"\x06UserId\x18\x02 \x01(\tR\x06UserId\x12\x12\n" +
	"\x04Urls\x18\x03 \x03(\tR\x04Urls\"'\n" +
	"\x11SetSubmissionResp\x12\x12\n" +
	"\x04Flag\x18\x01 \x01(\bR\x04Flag\"R\n" +
	"\x14GetSubmissionInfoReq\x12\"\n" +
	"\fAssignmentID\x18\x01 \x01(\tR\fAssignmentID\x12\x16\n" +
	"\x06UserId\x18\x02 \x01(\tR\x06UserId\"]\n" +
	"\x15GetSubmissionInfoResp\x12D\n" +
	"\x0fSubmissionInfos\x18\x01 \x03(\v2\x1a.submission.SubmissionInfoR\x0fSubmissionInfos\"\\\n" +
	"\x0eSubmissionInfo\x12\"\n" +
	"\fSubmissionID\x18\x01 \x01(\tR\fSubmissionID\x12\x12\n" +
	"\x04Urls\x18\x02 \x03(\tR\x04Urls\x12\x12\n" +
	"\x04Time\x18\x03 \x01(\tR\x04Time\"?\n" +
	"\x19GetAllSubmissionStatusReq\x12\"\n" +
	"\fAssignmentID\x18\x01 \x01(\tR\fAssignmentID\"\xc6\x01\n" +
	"\n" +
	"Completion\x12\x16\n" +
	"\x06UserId\x18\x01 \x01(\tR\x06UserId\x12\x12\n" +
	"\x04Name\x18\x02 \x01(\tR\x04Name\x12\x16\n" +
	"\x06Avatar\x18\x03 \x01(\tR\x06Avatar\x12\x14\n" +
	"\x05Email\x18\x04 \x01(\tR\x05Email\x12\x14\n" +
	"\x05Grade\x18\x05 \x01(\tR\x05Grade\x12\x16\n" +
	"\x06School\x18\x06 \x01(\tR\x06School\x12\x16\n" +
	"\x06Status\x18\a \x01(\tR\x06Status\x12\x18\n" +
	"\aversion\x18\b \x01(\x03R\aversion\"V\n" +
	"\x1aGetAllSubmissionStatusResp\x128\n" +
	"\vCompletions\x18\x01 \x03(\v2\x16.submission.CompletionR\vCompletions2\x89\x03\n" +
	"\x10submissionClient\x12d\n" +
	"\x15GetMySubmissionStatus\x12$.submission.GetMySubmissionStatusReq\x1a%.submission.GetMySubmissionStatusResp\x12L\n" +
	"\rSetSubmission\x12\x1c.submission.SetSubmissionReq\x1a\x1d.submission.SetSubmissionResp\x12X\n" +
	"\x11GetSubmissionInfo\x12 .submission.GetSubmissionInfoReq\x1a!.submission.GetSubmissionInfoResp\x12g\n" +
	"\x16GetAllSubmissionStatus\x12%.submission.GetAllSubmissionStatusReq\x1a&.submission.GetAllSubmissionStatusRespB\x06Z\x04./pbb\x06proto3"

var (
	file_submission_proto_rawDescOnce sync.Once
	file_submission_proto_rawDescData []byte
)

func file_submission_proto_rawDescGZIP() []byte {
	file_submission_proto_rawDescOnce.Do(func() {
		file_submission_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_submission_proto_rawDesc), len(file_submission_proto_rawDesc)))
	})
	return file_submission_proto_rawDescData
}

var file_submission_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_submission_proto_goTypes = []any{
	(*GetMySubmissionStatusReq)(nil),   // 0: submission.GetMySubmissionStatusReq
	(*GetMySubmissionStatusResp)(nil),  // 1: submission.GetMySubmissionStatusResp
	(*SetSubmissionReq)(nil),           // 2: submission.SetSubmissionReq
	(*SetSubmissionResp)(nil),          // 3: submission.SetSubmissionResp
	(*GetSubmissionInfoReq)(nil),       // 4: submission.GetSubmissionInfoReq
	(*GetSubmissionInfoResp)(nil),      // 5: submission.GetSubmissionInfoResp
	(*SubmissionInfo)(nil),             // 6: submission.SubmissionInfo
	(*GetAllSubmissionStatusReq)(nil),  // 7: submission.GetAllSubmissionStatusReq
	(*Completion)(nil),                 // 8: submission.Completion
	(*GetAllSubmissionStatusResp)(nil), // 9: submission.GetAllSubmissionStatusResp
}
var file_submission_proto_depIdxs = []int32{
	6, // 0: submission.GetSubmissionInfoResp.SubmissionInfos:type_name -> submission.SubmissionInfo
	8, // 1: submission.GetAllSubmissionStatusResp.Completions:type_name -> submission.Completion
	0, // 2: submission.submissionClient.GetMySubmissionStatus:input_type -> submission.GetMySubmissionStatusReq
	2, // 3: submission.submissionClient.SetSubmission:input_type -> submission.SetSubmissionReq
	4, // 4: submission.submissionClient.GetSubmissionInfo:input_type -> submission.GetSubmissionInfoReq
	7, // 5: submission.submissionClient.GetAllSubmissionStatus:input_type -> submission.GetAllSubmissionStatusReq
	1, // 6: submission.submissionClient.GetMySubmissionStatus:output_type -> submission.GetMySubmissionStatusResp
	3, // 7: submission.submissionClient.SetSubmission:output_type -> submission.SetSubmissionResp
	5, // 8: submission.submissionClient.GetSubmissionInfo:output_type -> submission.GetSubmissionInfoResp
	9, // 9: submission.submissionClient.GetAllSubmissionStatus:output_type -> submission.GetAllSubmissionStatusResp
	6, // [6:10] is the sub-list for method output_type
	2, // [2:6] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_submission_proto_init() }
func file_submission_proto_init() {
	if File_submission_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_submission_proto_rawDesc), len(file_submission_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_submission_proto_goTypes,
		DependencyIndexes: file_submission_proto_depIdxs,
		MessageInfos:      file_submission_proto_msgTypes,
	}.Build()
	File_submission_proto = out.File
	file_submission_proto_goTypes = nil
	file_submission_proto_depIdxs = nil
}
