// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type Comment struct {
	CommentID  string    `json:"comment_id"`
	Avatar     string    `json:"avatar"`
	NickName   string    `json:"nickname"`
	Name       string    `json:"name"`
	Group      string    `json:"group"`
	Content    string    `json:"content"`
	FatherID   string    `json:"father_id"`
	CreateTime string    `json:"create_time"`
	Replies    []Comment `json:"replies"`
}

type Completion struct {
	UserId  string `json:"user_id"`
	Name    string `json:"name"`
	Avatar  string `json:"avatar"`
	Email   string `json:"email"`
	Grade   string `json:"grade"`
	School  string `json:"school"`
	Status  string `json:"status,options=[yes,no]"`
	Version int64  `json:"version"`
}

type DelAssignmentReq struct {
	Authorization string `header:"Authorization"`
	AssignmentID  string `path:"id"`
}

type DelAssignmentResp struct {
	Flag bool `json:"flag"`
}

type DelSubmissionCommentReq struct {
	Authorization string `header:"Authorization"`
	CommentID     string `path:"id"`
}

type DelSubmissionCommentResp struct {
	Flag bool `json:"flag"`
}

type GetAllSubmissionStatusReq struct {
	Authorization string `header:"Authorization"`
	AssignmentID  string `path:"id"`
}

type GetAllSubmissionStatusResp struct {
	Completions []Completion `json:"completions"`
}

type GetAssignmentInfoReq struct {
	Authorization string `header:"Authorization"`
	AssignmentID  string `path:"id"`
}

type GetAssignmentInfoResp struct {
	TitleText string   `json:"title_text"`
	Content   string   `json:"content"`
	Urls      []string `json:"urls"`
	Deadline  string   `json:"deadline"`
	Year      string   `json:"year"`
	Semester  string   `json:"semester"`
}

type GetAssignmentListReq struct {
	Authorization string `header:"Authorization"`
	Group         string `form:"group,options=[Product,Design,Frontend,Backend,Android]"`
}

type GetAssignmentListResp struct {
	Titles []Title `json:"titles"`
}

type GetAssignmentListSelectedReq struct {
	Authorization string `header:"Authorization"`
	Group         string `form:"group,options=[Product,Design,Frontend,Backend,Android]"`
	Year          int    `form:"year"`
	Semester      string `form:"semester,options=[autumn,spring]"`
}

type GetAssignmentListSelectedResp struct {
	Titles []Title `json:"titles"`
}

type GetMySubmissionStatusReq struct {
	Authorization string `header:"Authorization"`
	AssignmentID  string `path:"id"`
}

type GetMySubmissionStatusResp struct {
	MySubmissionStatus string `json:"task_status,options=[notSubmitted,submitted,reviewed]"`
}

type GetSubmissionCommentReq struct {
	Authorization string `header:"Authorization"`
	SubmissionID  string `path:"id"`
}

type GetSubmissionCommentResp struct {
	Comments []Comment `json:"comments"`
}

type GetSubmissionInfoReq struct {
	Authorization string `header:"Authorization"`
	AssignmentID  string `form:"assigned_task_id"`
	UserId        string `form:"user_id"`
}

type GetSubmissionInfoResp struct {
	SubmissionInfos []SubmissionInfo `json:"submission_infos"`
}

type ReplySubmissionCommentReq struct {
	Authorization string `header:"Authorization"`
	SubmissionID  string `path:"id"`
	FatherID      string `json:"father_id"`
	Content       string `json:"content"`
}

type ReplySubmissionCommentResp struct {
	Flag bool `json:"flag"`
}

type SetAssignmentReq struct {
	Authorization string   `header:"Authorization"`
	AssignmentID  string   `json:"assignedTaskID,optional"`
	Group         string   `form:"group,options=[Product,Design,Frontend,Backend,Android]"`
	TitleText     string   `json:"title_text"`
	Content       string   `json:"content"`
	Urls          []string `json:"urls"`
	Year          int64    `json:"year"`
	Semester      string   `json:"semester,options=[autumn,spring]"`
	Deadline      string   `json:"deadline"`
}

type SetAssignmentResp struct {
	Flag bool `json:"flag"`
}

type SetSubmissionCommentReq struct {
	Authorization string `header:"Authorization"`
	SubmissionID  string `path:"id"`
	Content       string `json:"content"`
}

type SetSubmissionCommentResp struct {
	Flag bool `json:"flag"`
}

type SetSubmissionReq struct {
	Authorization string   `header:"Authorization"`
	AssignmentID  string   `json:"assignedTaskID,optional"`
	Urls          []string `json:"urls"`
}

type SetSubmissionResp struct {
	Flag bool `json:"flag"`
}

type SubmissionInfo struct {
	SubmissionID string   `json:"submission_id"`
	Urls         []string `json:"urls"`
	Time         string   `json:"time"`
}

type Title struct {
	ID   string `json:"id"`
	Text string `json:"text"`
}
